<!doctype html> <!-- фри маркер, чтобы работать с какими-либо передаваемыми данными -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="/static/css/main_page_unauthorized_global.css"/>
    <link rel="stylesheet" href="/static/css/main_page_unauthorized_index.css"/>
    <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Inter:wght@400&display=swap"
    />

</head>

<body>
<div class="group-parent">
    <div class="rectangle-parent">
        <div class="group-child"></div>
        <img class="icon" alt="" src="/static/img/main_page_unauthorized_public/89560-1@2x.png"/>
        <div class="custom">
            <img class="qrerrrguuxk-1-icon" alt="" src="/static/img/main_page_unauthorized_public/qrerrrguuxk-1@2x.png"/>
            <div class="div">МАМАфон</div>
        </div>
    </div>

    <div class="custom">
        <div class="div1">
            <p class="p">Качественная связь, быстрый интернет и выгодные тарифы.</p>
            <p class="p1">
          <span>
            <span class="span">МАМАфон</span>
            <span> - Твое время, твоя сеть! </span>
          </span>
            </p>
        </div>
        <a href="/login">
            <div class="rectangle-group">
                <button class="group-item">
                    <div class="div2">Попробовать</div>
                </button>
            </div>
        </a>
    </div>

</div>
</body>
</html>